### ISSUE TITLE
FileNotFoundError: XXXXX_fke.csv

### ISSUE THREAD

**Issue by jiananalvin** [Mathux/AMASS-Annotation-Unifier#2]
Hi, I encountered this issue. Could you please help me out? How can we get the `XXXXX_fke.csv` files? In KIT dataset, I only see these four formats. Thank you very much in advance! 😊
![image](https://github.com/user-attachments/assets/9fa3e7f8-0f6c-42a2-ba10-79f88356f7fe)

```
$ python ./kitml.py
  0%|                                                           | 0/3701 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/user/projects/amass-unifier/./kitml.py", line 82, in <module>
    process_kitml(amass_path, kitml_path, kitml_process_folder)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/projects/amass-unifier/./kitml.py", line 26, in process_kitml
    mmm = load_mmm_csv(csv_path)
  File "/home/user/projects/amass-unifier/tools/kitml.py", line 8, in load_mmm_csv
    xyzdata = pandas.read_csv(csv_path, index_col=0)
  File "/home/user/venvs/amass-unifier/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/user/venvs/amass-unifier/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/user/venvs/amass-unifier/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/user/venvs/amass-unifier/lib/python3.13/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ~~~~~~~~~~^
        f,
        ^^
    ...<6 lines>...
        storage_options=self.options.get("storage_options", None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/user/venvs/amass-unifier/lib/python3.13/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
        handle,
    ...<3 lines>...
        newline="",
    )
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/kit-mocap/02489_fke.csv'
```

**Comment by rcrandon** [comment]
I'm running into the exact same error when I try to run the ```python kitml.py``` cmd command.

Here's the error: 
```
 I'm running into the exact same error when I try to run the ```python kitml.py``` cmd command.

Here's the error: 
```
  0%|                                                                                         | 0/3701 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "%USERPROFILE%\Documents\data\AMASS-Annotation-Unifier\kitml.py", line 82, in <module>
    process_kitml(amass_path, kitml_path, kitml_process_folder)
  File "%USERPROFILE%\Documents\data\AMASS-Annotation-Unifier\kitml.py", line 26, in process_kitml
    mmm = load_mmm_csv(csv_path)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "%USERPROFILE%\Documents\data\AMASS-Annotation-Unifier\tools\kitml.py", line 8, in load_mmm_csv
    xyzdata = pandas.read_csv(csv_path, index_col=0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "%USERPROFILE%\Documents\data\AMASS-Annotation-Unifier\amass_venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "%USERPROFILE%\Documents\data\AMASS-Annotation-Unifier\amass_venv\Lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "%USERPROFILE%\Documents\data\AMASS-Annotation-Unifier\amass_venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "%USERPROFILE%\Documents\data\AMASS-Annotation-Unifier\amass_venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "%USERPROFILE%\Documents\data\AMASS-Annotation-Unifier\amass_venv\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/kit-mocap/02489_fke.csv'
```


```

**Comment by chaitanya100100** [comment]
@JiananAlvin @JiananAlvin Same error here. Any solution?

**Comment by chaitanya100100** [comment]
Solved it. Replace this code in kitml.py
```
        # csv_path = os.path.join(kitml_path, keyid + "_fke.csv")
        # mmm = load_mmm_csv(csv_path)
        xml_path = os.path.join(kitml_path, keyid + "_mmm.xml")
        with open(xml_path) as f:
            xml_data = f.read()
        soup = BeautifulSoup(xml_data, "xml")
        mmm = soup.find_all("MotionFrame")
```

**Comment by rp7sv** [comment]
> Solved it. Replace this code in kitml.py
> 
> ```
>         # csv_path = os.path.join(kitml_path, keyid + "_fke.csv")
>         # mmm = load_mmm_csv(csv_path)
>         xml_path = os.path.join(kitml_path, keyid + "_mmm.xml")
>         with open(xml_path) as f:
>             xml_data = f.read()
>         soup = BeautifulSoup(xml_data, "xml")
>         mmm = soup.find_all("MotionFrame")
> ```

Hi, what is `BeautifulSoup`?
